`timescale 1ns / 1ps

//------------------------------------------------------------------------------
// Compatibility top-level.  The real wiring-only top is node_top below.
//------------------------------------------------------------------------------
module node #(
    parameter SYNC_WORD    = 32'hA31E57BD,
    parameter BROADCAST    = 8'hFF,
    parameter MAX_PAYLOAD  = 256,
    parameter LIVENESS_WIN = 5,
    parameter NODE_COUNT   = 255,
    parameter DEDUP_DEPTH  = 64,
    parameter FIFO_DEPTH   = 8192,
    parameter RX_REPORT_FIFO_DEPTH = 2048,
    parameter CLK_FREQ_HZ  = 160_000_000,
    parameter CONGEST_TIMEOUT_SEC = 5
) (
    input  wire        clk,
    input  wire        rst,
    input  wire        node_id_valid,
    input  wire [7:0]  node_id,
    input  wire        rx_clk0,
    input  wire        rx_clk1,
    input  wire        tx_clk0,
    input  wire        tx_clk1,
    input  wire [31:0] in0,
    input  wire [31:0] in1,
    input  wire        valid_in0,
    input  wire        valid_in1,
    input  wire        app_frame_valid,
    output wire        app_frame_ready,
    output wire        app_frame_accepted,
    output wire        app_frame_done,
    input  wire [7:0]  app_dst_id,
    input  wire [15:0] app_len16,
    output wire [15:0] app_payload_addr,
    input  wire [31:0] app_payload_data,
    output wire        app_rx_frame_valid,
    input  wire        app_rx_frame_ready,
    output wire [7:0]  app_rx_src_id,
    output wire [7:0]  app_rx_dst_id,
    output wire [15:0] app_rx_count,
    output wire [15:0] app_rx_len16,
    output wire        app_rx_payload_valid,
    input  wire        app_rx_payload_ready,
    output wire [15:0] app_rx_payload_addr,
    output wire [31:0] app_rx_payload_data,
    output wire [31:0] out0,
    output wire [31:0] out1,
    output wire        valid_out0,
    output wire        valid_out1,
    output wire        liveness_valid,
    output wire [7:0]  liveness_node,
    output wire        liveness_alive,
    output wire        network_congested,
    output wire        app_len_error,
    output wire        rx_overflow
);
    node_top #(
        .SYNC_WORD(SYNC_WORD),
        .BROADCAST(BROADCAST),
        .MAX_PAYLOAD(MAX_PAYLOAD),
        .LIVENESS_WIN(LIVENESS_WIN),
        .NODE_COUNT(NODE_COUNT),
        .DEDUP_DEPTH(DEDUP_DEPTH),
        .FIFO_DEPTH(FIFO_DEPTH),
        .RX_REPORT_FIFO_DEPTH(RX_REPORT_FIFO_DEPTH),
        .CLK_FREQ_HZ(CLK_FREQ_HZ),
        .CONGEST_TIMEOUT_SEC(CONGEST_TIMEOUT_SEC)
    ) u_node_top (
        .clk(clk),
        .rst(rst),
        .node_id_valid(node_id_valid),
        .node_id(node_id),
        .rx_clk0(rx_clk0),
        .rx_clk1(rx_clk1),
        .tx_clk0(tx_clk0),
        .tx_clk1(tx_clk1),
        .in0(in0),
        .in1(in1),
        .valid_in0(valid_in0),
        .valid_in1(valid_in1),
        .app_frame_valid(app_frame_valid),
        .app_frame_ready(app_frame_ready),
        .app_frame_accepted(app_frame_accepted),
        .app_frame_done(app_frame_done),
        .app_dst_id(app_dst_id),
        .app_len16(app_len16),
        .app_payload_addr(app_payload_addr),
        .app_payload_data(app_payload_data),
        .app_rx_frame_valid(app_rx_frame_valid),
        .app_rx_frame_ready(app_rx_frame_ready),
        .app_rx_src_id(app_rx_src_id),
        .app_rx_dst_id(app_rx_dst_id),
        .app_rx_count(app_rx_count),
        .app_rx_len16(app_rx_len16),
        .app_rx_payload_valid(app_rx_payload_valid),
        .app_rx_payload_ready(app_rx_payload_ready),
        .app_rx_payload_addr(app_rx_payload_addr),
        .app_rx_payload_data(app_rx_payload_data),
        .out0(out0),
        .out1(out1),
        .valid_out0(valid_out0),
        .valid_out1(valid_out1),
        .liveness_valid(liveness_valid),
        .liveness_node(liveness_node),
        .liveness_alive(liveness_alive),
        .network_congested(network_congested),
        .app_len_error(app_len_error),
        .rx_overflow(rx_overflow)
    );
endmodule
