`timescale 1ns / 1ps

// Simple user-data demo for gtwizard_0_user_exdes.
//
// Per lane packet format:
//   idle:    K28.5 bytes, generated by gtwizard_0_user_exdes when TX_VALID=0
//   SOF:     one low-byte K27.7, TXDATA=32'h000000fb, TXCHARISK=4'b0001
//   payload: FRAME_WORDS words, TXCHARISK=4'b0000
//   EOF:     one low-byte K29.7, TXDATA=32'h000000fd, TXCHARISK=4'b0001
//
// RX logic discards idle/control characters, uses SOF/EOF to frame payload,
// and exposes simple counters plus the last received payload word.

module gtwizard_0_user_demo #
(
    parameter integer FRAME_WORDS = 16,
    parameter integer IDLE_WORDS  = 16
)
(
    input  wire        Q3_CLK0_GTREFCLK_PAD_N_IN,
    input  wire        Q3_CLK0_GTREFCLK_PAD_P_IN,
    input  wire        DRP_CLK_IN_P,
    input  wire        DRP_CLK_IN_N,

    input  wire [1:0]  RXN_IN,
    input  wire [1:0]  RXP_IN,
    output wire [1:0]  TXN_OUT,
    output wire [1:0]  TXP_OUT,
    output wire [1:0]  sfp_tx_disable,

    output wire        gt0_link_ready,
    output wire        gt1_link_ready,
    output wire [31:0] gt0_rx_last_word,
    output wire [31:0] gt1_rx_last_word,
    output wire [31:0] gt0_rx_word_count,
    output wire [31:0] gt1_rx_word_count,
    output wire [31:0] gt0_rx_frame_count,
    output wire [31:0] gt1_rx_frame_count,
    output wire [31:0] gt0_rx_error_count,
    output wire [31:0] gt1_rx_error_count
);

    localparam [7:0] K_SOF = 8'hfb; // K27.7
    localparam [7:0] K_EOF = 8'hfd; // K29.7

    wire        gt0_tx_clk;
    wire        gt0_rx_clk;
    wire        gt1_tx_clk;
    wire        gt1_rx_clk;
    wire        gt0_tx_reset;
    wire        gt0_rx_reset;
    wire        gt1_tx_reset;
    wire        gt1_rx_reset;
    wire        gt0_tx_ready;
    wire        gt0_rx_ready;
    wire        gt1_tx_ready;
    wire        gt1_rx_ready;

    wire [31:0] gt0_rxdata;
    wire [3:0]  gt0_rxcharisk;
    wire [3:0]  gt0_rxdisperr;
    wire [3:0]  gt0_rxnotintable;
    wire        gt0_rx_valid;
    wire [31:0] gt1_rxdata;
    wire [3:0]  gt1_rxcharisk;
    wire [3:0]  gt1_rxdisperr;
    wire [3:0]  gt1_rxnotintable;
    wire        gt1_rx_valid;

    wire [31:0] gt0_txdata;
    wire [3:0]  gt0_txcharisk;
    wire        gt0_tx_valid;
    wire [31:0] gt1_txdata;
    wire [3:0]  gt1_txcharisk;
    wire        gt1_tx_valid;

    assign gt0_link_ready = gt0_tx_ready & gt0_rx_ready;
    assign gt1_link_ready = gt1_tx_ready & gt1_rx_ready;

    gtwizard_0_user_exdes u_gt
    (
        .Q3_CLK0_GTREFCLK_PAD_N_IN(Q3_CLK0_GTREFCLK_PAD_N_IN),
        .Q3_CLK0_GTREFCLK_PAD_P_IN(Q3_CLK0_GTREFCLK_PAD_P_IN),
        .DRP_CLK_IN_P(DRP_CLK_IN_P),
        .DRP_CLK_IN_N(DRP_CLK_IN_N),
        .RXN_IN(RXN_IN),
        .RXP_IN(RXP_IN),
        .TXN_OUT(TXN_OUT),
        .TXP_OUT(TXP_OUT),
        .sfp_tx_disable(sfp_tx_disable),

        .USER_GT0_TXDATA_IN(gt0_txdata),
        .USER_GT0_TXCHARISK_IN(gt0_txcharisk),
        .USER_GT0_TX_VALID_IN(gt0_tx_valid),
        .USER_GT1_TXDATA_IN(gt1_txdata),
        .USER_GT1_TXCHARISK_IN(gt1_txcharisk),
        .USER_GT1_TX_VALID_IN(gt1_tx_valid),

        .USER_GT0_RXDATA_OUT(gt0_rxdata),
        .USER_GT0_RXCHARISK_OUT(gt0_rxcharisk),
        .USER_GT0_RXDISPERR_OUT(gt0_rxdisperr),
        .USER_GT0_RXNOTINTABLE_OUT(gt0_rxnotintable),
        .USER_GT0_RX_VALID_OUT(gt0_rx_valid),
        .USER_GT1_RXDATA_OUT(gt1_rxdata),
        .USER_GT1_RXCHARISK_OUT(gt1_rxcharisk),
        .USER_GT1_RXDISPERR_OUT(gt1_rxdisperr),
        .USER_GT1_RXNOTINTABLE_OUT(gt1_rxnotintable),
        .USER_GT1_RX_VALID_OUT(gt1_rx_valid),

        .USER_GT0_TXUSRCLK2_OUT(gt0_tx_clk),
        .USER_GT0_RXUSRCLK2_OUT(gt0_rx_clk),
        .USER_GT1_TXUSRCLK2_OUT(gt1_tx_clk),
        .USER_GT1_RXUSRCLK2_OUT(gt1_rx_clk),
        .USER_GT0_TX_RESET_OUT(gt0_tx_reset),
        .USER_GT0_RX_RESET_OUT(gt0_rx_reset),
        .USER_GT1_TX_RESET_OUT(gt1_tx_reset),
        .USER_GT1_RX_RESET_OUT(gt1_rx_reset),
        .USER_GT0_TX_READY_OUT(gt0_tx_ready),
        .USER_GT0_RX_READY_OUT(gt0_rx_ready),
        .USER_GT1_TX_READY_OUT(gt1_tx_ready),
        .USER_GT1_RX_READY_OUT(gt1_rx_ready)
    );

    simple_8b10b_packet_tx #(
        .LANE_ID(8'h00),
        .FRAME_WORDS(FRAME_WORDS),
        .IDLE_WORDS(IDLE_WORDS)
    ) u_gt0_tx (
        .clk(gt0_tx_clk),
        .rst(gt0_tx_reset),
        .ready(gt0_tx_ready),
        .txdata(gt0_txdata),
        .txcharisk(gt0_txcharisk),
        .tx_valid(gt0_tx_valid)
    );

    simple_8b10b_packet_tx #(
        .LANE_ID(8'h01),
        .FRAME_WORDS(FRAME_WORDS),
        .IDLE_WORDS(IDLE_WORDS)
    ) u_gt1_tx (
        .clk(gt1_tx_clk),
        .rst(gt1_tx_reset),
        .ready(gt1_tx_ready),
        .txdata(gt1_txdata),
        .txcharisk(gt1_txcharisk),
        .tx_valid(gt1_tx_valid)
    );

    simple_8b10b_packet_rx u_gt0_rx (
        .clk(gt0_rx_clk),
        .rst(gt0_rx_reset),
        .ready(gt0_rx_ready),
        .rx_valid(gt0_rx_valid),
        .rxdata(gt0_rxdata),
        .rxcharisk(gt0_rxcharisk),
        .rxdisperr(gt0_rxdisperr),
        .rxnotintable(gt0_rxnotintable),
        .last_word(gt0_rx_last_word),
        .word_count(gt0_rx_word_count),
        .frame_count(gt0_rx_frame_count),
        .error_count(gt0_rx_error_count)
    );

    simple_8b10b_packet_rx u_gt1_rx (
        .clk(gt1_rx_clk),
        .rst(gt1_rx_reset),
        .ready(gt1_rx_ready),
        .rx_valid(gt1_rx_valid),
        .rxdata(gt1_rxdata),
        .rxcharisk(gt1_rxcharisk),
        .rxdisperr(gt1_rxdisperr),
        .rxnotintable(gt1_rxnotintable),
        .last_word(gt1_rx_last_word),
        .word_count(gt1_rx_word_count),
        .frame_count(gt1_rx_frame_count),
        .error_count(gt1_rx_error_count)
    );

endmodule


module simple_8b10b_packet_tx #
(
    parameter [7:0]   LANE_ID     = 8'h00,
    parameter integer FRAME_WORDS = 16,
    parameter integer IDLE_WORDS  = 16
)
(
    input  wire        clk,
    input  wire        rst,
    input  wire        ready,
    output reg  [31:0] txdata,
    output reg  [3:0]  txcharisk,
    output reg         tx_valid
);

    localparam [1:0] ST_IDLE    = 2'd0;
    localparam [1:0] ST_SOF     = 2'd1;
    localparam [1:0] ST_PAYLOAD = 2'd2;
    localparam [1:0] ST_EOF     = 2'd3;

    localparam [7:0] K_SOF = 8'hfb; // K27.7
    localparam [7:0] K_EOF = 8'hfd; // K29.7

    reg [1:0]  state = ST_IDLE;
    reg [15:0] idle_cnt = 16'd0;
    reg [15:0] word_idx = 16'd0;
    reg [15:0] frame_idx = 16'd0;

    always @(posedge clk) begin
        if (rst || !ready) begin
            state     <= ST_IDLE;
            idle_cnt  <= 16'd0;
            word_idx  <= 16'd0;
            frame_idx <= 16'd0;
            txdata    <= 32'd0;
            txcharisk <= 4'b0000;
            tx_valid  <= 1'b0;
        end else begin
            case (state)
                ST_IDLE: begin
                    tx_valid  <= 1'b0; // wrapper sends K28.5 idle
                    txdata    <= 32'd0;
                    txcharisk <= 4'b0000;
                    if (idle_cnt == (IDLE_WORDS - 1)) begin
                        idle_cnt <= 16'd0;
                        state    <= ST_SOF;
                    end else begin
                        idle_cnt <= idle_cnt + 1'b1;
                    end
                end

                ST_SOF: begin
                    tx_valid  <= 1'b1;
                    txdata    <= {24'd0, K_SOF};
                    txcharisk <= 4'b0001;
                    word_idx  <= 16'd0;
                    state     <= ST_PAYLOAD;
                end

                ST_PAYLOAD: begin
                    tx_valid  <= 1'b1;
                    txdata    <= {LANE_ID, frame_idx[7:0], word_idx};
                    txcharisk <= 4'b0000;
                    if (word_idx == (FRAME_WORDS - 1)) begin
                        word_idx <= 16'd0;
                        state    <= ST_EOF;
                    end else begin
                        word_idx <= word_idx + 1'b1;
                    end
                end

                ST_EOF: begin
                    tx_valid  <= 1'b1;
                    txdata    <= {24'd0, K_EOF};
                    txcharisk <= 4'b0001;
                    frame_idx <= frame_idx + 1'b1;
                    state     <= ST_IDLE;
                end

                default: begin
                    state    <= ST_IDLE;
                    tx_valid <= 1'b0;
                end
            endcase
        end
    end

endmodule


module simple_8b10b_packet_rx
(
    input  wire        clk,
    input  wire        rst,
    input  wire        ready,
    input  wire        rx_valid,
    input  wire [31:0] rxdata,
    input  wire [3:0]  rxcharisk,
    input  wire [3:0]  rxdisperr,
    input  wire [3:0]  rxnotintable,
    output reg  [31:0] last_word,
    output reg  [31:0] word_count,
    output reg  [31:0] frame_count,
    output reg  [31:0] error_count
);

    localparam [7:0] K_IDLE = 8'hbc; // K28.5
    localparam [7:0] K_SOF  = 8'hfb; // K27.7
    localparam [7:0] K_EOF  = 8'hfd; // K29.7

    reg in_frame = 1'b0;

    wire code_error = |rxdisperr | |rxnotintable;
    wire low_byte_k = rxcharisk[0];
    wire got_idle   = (rxcharisk == 4'b1111) && (rxdata == {K_IDLE, K_IDLE, K_IDLE, K_IDLE});
    wire got_sof    = low_byte_k && (rxdata[7:0] == K_SOF);
    wire got_eof    = low_byte_k && (rxdata[7:0] == K_EOF);

    always @(posedge clk) begin
        if (rst || !ready) begin
            in_frame    <= 1'b0;
            last_word   <= 32'd0;
            word_count  <= 32'd0;
            frame_count <= 32'd0;
            error_count <= 32'd0;
        end else if (rx_valid) begin
            if (code_error) begin
                error_count <= error_count + 1'b1;
                in_frame    <= 1'b0;
            end else if (got_sof) begin
                in_frame <= 1'b1;
            end else if (got_eof) begin
                if (in_frame) begin
                    frame_count <= frame_count + 1'b1;
                end
                in_frame <= 1'b0;
            end else if (got_idle) begin
                in_frame <= in_frame;
            end else if (in_frame && (rxcharisk == 4'b0000)) begin
                last_word  <= rxdata;
                word_count <= word_count + 1'b1;
            end else if (rxcharisk != 4'b0000) begin
                error_count <= error_count + 1'b1;
                in_frame    <= 1'b0;
            end
        end
    end

endmodule
